image: python:{{ cookiecutter.python_version }}

stages:
  - test
  - build
  - staging
  - production

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh/tmp/
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'

test:
  tags:
    - docker
  stage: test
  script:
    - python{{ cookiecutter.python_version }} -m pip install --user detox
    - $HOME/.local/bin/detox -v

build:
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - python3 setup.py sdist
  artifacts:
    paths:
      - dist/

deploy to staging:
  tags:
    - docker
  stage: staging
  only:
    - master
  script:
    - echo 'Put here your deploy script for development.'

deploy to production:
  tags:
    - typhon_whitelisted
  stage: production
  only:
    -master
  when: manual
  script:
    - echo 'Put here your deploy script for production.'